### ISSUE TITLE
Feature: ApiKey Model for Managing API Keys

### ISSUE THREAD

**Issue by thenoblet** [thenoblet/inventorywise#12]
#### Description
This issue outlines the implementation of an `ApiKey` model designed to manage API keys within the application. The model will provide essential functionality for generating, storing, and managing API keys for various applications and users. 

#### Features
- **Key Generation:** Securely generate unique API keys for users and applications.
- **Key Storage:** Store both the API key and its hashed version for security.
- **Rate Limiting:** Implement functionality to control the number of requests allowed per hour, enhancing the security of API usage.
- **Usage Tracking:** Track how often an API key has been used and the last time it was accessed.
- **Key Expiration:** Include a mechanism to check whether an API key has expired.
- **Key Regeneration:** Allow users to regenerate lost or compromised keys while maintaining ownership and settings.

#### Model Overview
The `ApiKey` model will consist of the following fields:
- `key`: A unique, uneditable string representing the API key.
- `hashed_key`: A hashed version of the API key for secure storage.
- `app_id`: A unique identifier for the application associated with the API key.
- `owner`: A foreign key linking the API key to a user.
- `is_active`: A boolean indicating whether the API key is active.
- `created_at`: A timestamp for when the API key was created.
- `rate_limit`: An integer representing the number of allowed requests per hour.
- `last_used`: A timestamp for the last time the API key was used.
- `usage_count`: An integer tracking how many times the API key has been used.

#### Benefits
Implementing this `ApiKey` model will enhance the application's API management capabilities by:
- Providing secure API key generation and management.
- Allowing for better control over API usage through rate limiting.
- Improving security by tracking key usage and supporting key regeneration.

#### Next Steps
- Design and implement the `ApiKey` model as outlined above.
- Write tests to ensure that all features work as expected.

**Comment by LawsonLawson** [comment]
👍👍👍
